/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.Dj_Usuarios;
import dao.Dj_UsuariosDao;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class JDlgUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        Habilitar(false);
    }
    
    public void Habilitar(boolean value){
        jTxt_Apelido.setEnabled(value);
        jTxt_Nome.setEnabled(value);
        jCbo_Nivel.setEnabled(value);
        jChb_Ativo.setEnabled(value);
        jFmt_Cpf.setEnabled(value);
        jFmt_DataNascimento.setEnabled(value);
        jPwd_Senha.setEnabled(value);
        jTxt_Codigo.setEnabled(value);
        jBtn_Cancelar.setEnabled(value);
        jBtn_Confirmar.setEnabled(value);
        jBtn_Excluir.setEnabled(!value);
        jBtn_Incluir.setEnabled(!value);
        jBtn_Alterar.setEnabled(!value);
        jBtn_Pesquisar.setEnabled(!value);
    }
    
    public void limpar(){
        jTxt_Codigo.setText("");
        jTxt_Nome.setText("");
        jTxt_Apelido.setText("");
        jFmt_Cpf.setText("");
        jFmt_DataNascimento.setText("");
        jPwd_Senha.setText("");
        jCbo_Nivel.setSelectedIndex(-1);
        jChb_Ativo.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNome = new javax.swing.JLabel();
        jTxt_Nome = new javax.swing.JTextField();
        jLblApelido = new javax.swing.JLabel();
        jTxt_Apelido = new javax.swing.JTextField();
        jLblCpf = new javax.swing.JLabel();
        jFmt_Cpf = new javax.swing.JFormattedTextField();
        jLblDataNascimento = new javax.swing.JLabel();
        jFmt_DataNascimento = new javax.swing.JFormattedTextField();
        jLblSenha = new javax.swing.JLabel();
        jPwd_Senha = new javax.swing.JPasswordField();
        jLblNivel = new javax.swing.JLabel();
        jChb_Ativo = new javax.swing.JCheckBox();
        jCbo_Nivel = new javax.swing.JComboBox<>();
        jBtn_Alterar = new javax.swing.JButton();
        jBtn_Excluir = new javax.swing.JButton();
        jBtn_Confirmar = new javax.swing.JButton();
        jBtn_Cancelar = new javax.swing.JButton();
        jBtn_Incluir = new javax.swing.JButton();
        jBtn_Pesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxt_Codigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(345, 275));

        jLblNome.setText("Nome");

        jTxt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_NomeActionPerformed(evt);
            }
        });

        jLblApelido.setText("Apelido");

        jTxt_Apelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_ApelidoActionPerformed(evt);
            }
        });

        jLblCpf.setText("CPF");

        try {
            jFmt_Cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblDataNascimento.setText("Data de nascimento");

        try {
            jFmt_DataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblSenha.setText("Senha");

        jLblNivel.setText("Nível");

        jChb_Ativo.setText("Ativo");

        jCbo_Nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Convidado", "Cliente", "Vendedor", "Administrador", "Fornecedor" }));
        jCbo_Nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbo_NivelActionPerformed(evt);
            }
        });

        jBtn_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-alter-24.png"))); // NOI18N
        jBtn_Alterar.setText("Alterar");
        jBtn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AlterarActionPerformed(evt);
            }
        });

        jBtn_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-entrada-proibida-24.png"))); // NOI18N
        jBtn_Excluir.setText("Exluir");
        jBtn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ExcluirActionPerformed(evt);
            }
        });

        jBtn_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-botão-de-opção-marcado-24.png"))); // NOI18N
        jBtn_Confirmar.setText("Confirmar");
        jBtn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ConfirmarActionPerformed(evt);
            }
        });

        jBtn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancelar-24.png"))); // NOI18N
        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jBtn_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-mais-24.png"))); // NOI18N
        jBtn_Incluir.setText("incluir");
        jBtn_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_IncluirActionPerformed(evt);
            }
        });

        jBtn_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pesquisar-24.png"))); // NOI18N
        jBtn_Pesquisar.setText("Pesquisar");
        jBtn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jTxt_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_CodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbo_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jChb_Ativo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPwd_Senha)
                    .addComponent(jTxt_Codigo)
                    .addComponent(jTxt_Nome)
                    .addComponent(jTxt_Apelido)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblDataNascimento)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jFmt_DataNascimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblApelido))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblApelido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblDataNascimento)
                            .addComponent(jLblCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmt_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFmt_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSenha)
                    .addComponent(jCbo_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNivel)
                    .addComponent(jChb_Ativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPwd_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn_Confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtn_Pesquisar)
                        .addComponent(jBtn_Cancelar)
                        .addComponent(jBtn_Excluir)
                        .addComponent(jBtn_Incluir)
                        .addComponent(jBtn_Alterar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_NomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxt_NomeActionPerformed

    private void jCbo_NivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbo_NivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbo_NivelActionPerformed

    private void jTxt_ApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_ApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_ApelidoActionPerformed

    private void jBtn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ExcluirActionPerformed
        // TODO add your handling code here:
            int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão ?","Atenção", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION){
                Dj_Usuarios dj_usuarios = new Dj_Usuarios();
                int codigo = Integer.parseInt(jTxt_Codigo.getText());
                dj_usuarios.setDj_idUsuarios(codigo);
                dj_usuarios.setDj_nome(jTxt_Nome.getText() );
                dj_usuarios.setDj_apelido(jTxt_Apelido.getText() );
                dj_usuarios.setDj_cpf(jFmt_Cpf.getText() );
                dj_usuarios.setDj_dataNascimento(null);
                dj_usuarios.setDj_senha(jPwd_Senha.getText() );
                dj_usuarios.setDj_nivel(jCbo_Nivel.getSelectedIndex());
                if (jChb_Ativo.isSelected() == true){
                    dj_usuarios.setDj_ativo("S");
                } else {
                    dj_usuarios.setDj_ativo("N");
                }
                Dj_UsuariosDao usuariosDao = new Dj_UsuariosDao();
                usuariosDao.delete(dj_usuarios);
            }
            limpar();
    }//GEN-LAST:event_jBtn_ExcluirActionPerformed

    private void jBtn_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_IncluirActionPerformed
        // TODO add your handling code here:
        limpar();
        Habilitar(true);
    }//GEN-LAST:event_jBtn_IncluirActionPerformed

    private void jBtn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ConfirmarActionPerformed
        // TODO add your handling code here:
        Dj_Usuarios dj_usuarios = new Dj_Usuarios();
        int codigo = Integer.parseInt(jTxt_Codigo.getText());
        dj_usuarios.setDj_idUsuarios(codigo);
        dj_usuarios.setDj_nome(jTxt_Nome.getText() );
        dj_usuarios.setDj_apelido(jTxt_Apelido.getText() );
        dj_usuarios.setDj_cpf(jFmt_Cpf.getText() );
        dj_usuarios.setDj_dataNascimento(null);
        dj_usuarios.setDj_senha(jPwd_Senha.getText() );
        dj_usuarios.setDj_nivel(jCbo_Nivel.getSelectedIndex());
        if (jChb_Ativo.isSelected() == true){
            dj_usuarios.setDj_ativo("S");
        } else {
            dj_usuarios.setDj_ativo("N");
        }
        Dj_UsuariosDao usuariosDao = new Dj_UsuariosDao();
        usuariosDao.insert(dj_usuarios);
        limpar();
        Habilitar(false);
    }//GEN-LAST:event_jBtn_ConfirmarActionPerformed

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        // TODO add your handling code here:
        limpar();
        Habilitar(false);
    }//GEN-LAST:event_jBtn_CancelarActionPerformed

    private void jBtn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PesquisarActionPerformed
        // TODO add your handling code here:
        String id = JOptionPane.showInputDialog(null, "Pesquisar o código");
        int codigo = Integer.parseInt(id);
        Dj_UsuariosDao usuariosDao = new Dj_UsuariosDao();
        Dj_Usuarios dj_usuarios = (Dj_Usuarios) usuariosDao.list(codigo);
        if (dj_usuarios == null){
            JOptionPane.showMessageDialog(null, "Códgio não existe");
        } else{
        jTxt_Codigo.setText(id);
        jTxt_Nome.setText(dj_usuarios.getDj_nome());
        jTxt_Apelido.setText(dj_usuarios.getDj_apelido());
        jFmt_Cpf.setText(dj_usuarios.getDj_cpf());
//        jFmt_DataNascimento.setText(dj_usuarios.getDj_dataNascimento());
        jPwd_Senha.setText(dj_usuarios.getDj_senha());
        jCbo_Nivel.setSelectedIndex(dj_usuarios.getDj_nivel());
        if (dj_usuarios.getDj_ativo().equals("S")) {
            jChb_Ativo.setSelected(true);
        }else{
            jChb_Ativo.setSelected(false);        
        }
    }
    }//GEN-LAST:event_jBtn_PesquisarActionPerformed

    private void jBtn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AlterarActionPerformed
        // TODO add your handling code here:
        limpar();
        Habilitar(true);
    }//GEN-LAST:event_jBtn_AlterarActionPerformed

    private void jTxt_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_CodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxt_CodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Alterar;
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Confirmar;
    private javax.swing.JButton jBtn_Excluir;
    private javax.swing.JButton jBtn_Incluir;
    private javax.swing.JButton jBtn_Pesquisar;
    private javax.swing.JComboBox<String> jCbo_Nivel;
    private javax.swing.JCheckBox jChb_Ativo;
    private javax.swing.JFormattedTextField jFmt_Cpf;
    private javax.swing.JFormattedTextField jFmt_DataNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblApelido;
    private javax.swing.JLabel jLblCpf;
    private javax.swing.JLabel jLblDataNascimento;
    private javax.swing.JLabel jLblNivel;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblSenha;
    private javax.swing.JPasswordField jPwd_Senha;
    private javax.swing.JTextField jTxt_Apelido;
    private javax.swing.JTextField jTxt_Codigo;
    private javax.swing.JTextField jTxt_Nome;
    // End of variables declaration//GEN-END:variables
}
