/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author danie
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Sistema de compras de flores artificiais");
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnu_Cadastro = new javax.swing.JMenu();
        jMni_Usuario = new javax.swing.JMenuItem();
        jMni_Vendedor = new javax.swing.JMenuItem();
        jMni_Fornecedor = new javax.swing.JMenuItem();
        jMni_Produtos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMni_Sair = new javax.swing.JMenuItem();
        jMnu_Movimento = new javax.swing.JMenu();
        jMni_ComprasProdutos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMni_Compras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnu_Cadastro.setText("Cadastro");

        jMni_Usuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-usuário-24.png"))); // NOI18N
        jMni_Usuario.setText("Usuario");
        jMni_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_UsuarioActionPerformed(evt);
            }
        });
        jMnu_Cadastro.add(jMni_Usuario);

        jMni_Vendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pessoa-24.png"))); // NOI18N
        jMni_Vendedor.setText("Vendedor");
        jMni_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_VendedorActionPerformed(evt);
            }
        });
        jMnu_Cadastro.add(jMni_Vendedor);

        jMni_Fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-fornecedor-24.png"))); // NOI18N
        jMni_Fornecedor.setText("Fornecedor");
        jMni_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_FornecedorActionPerformed(evt);
            }
        });
        jMnu_Cadastro.add(jMni_Fornecedor);

        jMni_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-flores-24.png"))); // NOI18N
        jMni_Produtos.setText("Produtos");
        jMni_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_ProdutosActionPerformed(evt);
            }
        });
        jMnu_Cadastro.add(jMni_Produtos);
        jMnu_Cadastro.add(jSeparator1);

        jMni_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-exportar-24.png"))); // NOI18N
        jMni_Sair.setText("Sair");
        jMni_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_SairActionPerformed(evt);
            }
        });
        jMnu_Cadastro.add(jMni_Sair);

        jMenuBar1.add(jMnu_Cadastro);

        jMnu_Movimento.setText("Movimento");
        jMnu_Movimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnu_MovimentoActionPerformed(evt);
            }
        });

        jMni_ComprasProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_ComprasProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-produto-24.png"))); // NOI18N
        jMni_ComprasProdutos.setText("Compras Produtos");
        jMni_ComprasProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_ComprasProdutosActionPerformed(evt);
            }
        });
        jMnu_Movimento.add(jMni_ComprasProdutos);
        jMnu_Movimento.add(jSeparator2);

        jMni_Compras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-carrinho-de-compras-24.png"))); // NOI18N
        jMni_Compras.setText("Compras");
        jMnu_Movimento.add(jMni_Compras);

        jMenuBar1.add(jMnu_Movimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMni_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_UsuarioActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(null, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMni_UsuarioActionPerformed

    private void jMni_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_VendedorActionPerformed
        // TODO add your handling code here:
        JDlgVendedor jDlgVendedor = new JDlgVendedor(null, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMni_VendedorActionPerformed

    private void jMni_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_FornecedorActionPerformed
        // TODO add your handling code here:
        JDlgFornecedor jDlgFornecedor = new JDlgFornecedor(null, true);
        jDlgFornecedor.setVisible(true);
    }//GEN-LAST:event_jMni_FornecedorActionPerformed

    private void jMni_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_ProdutosActionPerformed
        // TODO add your handling code here:
        JDlgProdutos jDlgProdutos = new JDlgProdutos(null, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMni_ProdutosActionPerformed

    private void jMnu_MovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnu_MovimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnu_MovimentoActionPerformed

    private void jMni_ComprasProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_ComprasProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMni_ComprasProdutosActionPerformed

    private void jMni_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMni_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMni_Compras;
    private javax.swing.JMenuItem jMni_ComprasProdutos;
    private javax.swing.JMenuItem jMni_Fornecedor;
    private javax.swing.JMenuItem jMni_Produtos;
    private javax.swing.JMenuItem jMni_Sair;
    private javax.swing.JMenuItem jMni_Usuario;
    private javax.swing.JMenuItem jMni_Vendedor;
    private javax.swing.JMenu jMnu_Cadastro;
    private javax.swing.JMenu jMnu_Movimento;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
